---

-  hosts: CentOS
   become: true
   tasks:

   - name: Creation of Prometheus download directory in CentOS
     file:
       path: ~/prometheus
       mode: 0777
       state: directory

   - name: Creation of Prometheus Library Directories in CentOS
     file:
       path:
         - /etc/prometheus
         - /var/lib/prometheus
       mode: 0777
       state: directory

   - name: Installation of Prometheus in CentOS
     unarchive:
       src: https://github.com/prometheus/prometheus/releases/download/v2.8.1/prometheus-2.8.1.linux-amd64.tar.gz
       dest: ~/prometheus
       remote_src: yes
       mode: 0777
       owner: root
       group: root

   - name: Copying Files from Prometheus Directory to others in CentOS
     shell: |
       cd ~/prometheus/prometheus*
       cp -r prometheus /usr/local/bin/
       cp -r promtool /usr/local/bin/
       cp -r consoles /etc/prometheus
       cp -r console_libraries /etc/prometheus

   - name: Copy Configuration of Prometheus to etc/prometheus/ in CentOS
     copy:
       src: prometheus.yml
       dest: /etc/prometheus
       mode: 7777
       owner: root
       group: root

   - name: Copy Configuration of Prometheus Service to /etc/systemd/system/ in CentOS
     copy:
       src: prometheus.service
       dest: /etc/systemd/system
       mode: 7777
       owner: root
       group: root

   - name: Reload systemd service in CentOS
     shell: |
       systemctl daemon-reload

   - name: Enable HTTPD in CentOS
     service:
       name: httpd
       state: restarted
       enabled: true

   - name: Enable Prometheus Service in CentOS
     service:
       name: prometheus
       state: restarted
       enabled: true

   - name: Enable 9090/tcp Port for Prometheus in CentOS
     shell: |
       firewall-cmd --zone=public --add-port=9090/tcp --permanent

   - name: Reload Firewalld Service in CentOS
     service:
       name: firewalld
       state: restarted
       enabled: true

