---

-  hosts: all
   become: true
   pre_tasks:

   -  name: Update Repository Index
      tags: always
      package:
        update_cache: yes
      changed_when: false

-  hosts: Ubuntu
   become: true
   roles:
    - Ubuntu

-  hosts: CentOS
   become: true
   roles:
    - CentOS
